# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxx_solve_huber_nuclear <- function(Z, t, lambda, tol, maxIter, verbose = FALSE) {
    .Call(`_drrglm_cxx_solve_huber_nuclear`, Z, t, lambda, tol, maxIter, verbose)
}

cxx_solve_prox <- function(Z, lambda1, lambda2, tol, maxIter) {
    .Call(`_drrglm_cxx_solve_prox`, Z, lambda1, lambda2, tol, maxIter)
}

